import type { HostOrganization, Opportunity, Review } from "./types"

export const hostOrganizations: HostOrganization[] = [
  {
    id: "gkf",
    name: "GKF (Grace Kennett Foundation)",
    description:
      "Grace Kennett Foundation empowers communities through education, sustainable development, and social welfare initiatives. Based in Madurai, India, we work to create lasting positive change.",
    location: "Madurai, India",
    country: "India",
    logo: "/gkf-logo.webp",
    coverImage: "/indian-school-children-learning-classroom.jpg",
    rating: 4.8,
    reviewCount: 127,
    verified: true,
  },
  {
    id: "wildlife-africa",
    name: "Wildlife Conservation Africa",
    description: "Dedicated to protecting endangered species and preserving natural habitats across East Africa.",
    location: "Nairobi, Kenya",
    country: "Kenya",
    logo: "/wildlife-conservation-logo-elephant.jpg",
    coverImage: "/african-savanna-elephants-wildlife.jpg",
    rating: 4.9,
    reviewCount: 203,
    verified: true,
  },
  {
    id: "heritage-peru",
    name: "Heritage Preservation Peru",
    description: "Protecting and restoring ancient archaeological sites and promoting cultural heritage education.",
    location: "Cusco, Peru",
    country: "Peru",
    logo: "/heritage-preservation-logo-ancient-ruins.jpg",
    coverImage: "/machu-picchu-ancient-ruins-peru.jpg",
    rating: 4.7,
    reviewCount: 89,
    verified: true,
  },
]

export const opportunities: Opportunity[] = [
  {
    id: "gkf-education-1",
    hostId: "gkf",
    title: "Teaching English & Life Skills to Underprivileged Children",
    description:
      "Join our team in Madurai to teach English, mathematics, and life skills to children from underserved communities. Make a lasting impact on young lives while experiencing Indian culture.",
    theme: ["education", "childcare", "community"],
    location: "Madurai, India",
    country: "India",
    applicantTypes: ["volunteer", "intern"],
    minDuration: 4,
    maxDuration: 24,
    images: [
      "/teacher-with-indian-children-classroom.jpg",
      "/children-learning-english-india.jpg",
      "/volunteer-teaching-kids-mumbai.jpg",
    ],
    requirements: [
      "Fluent in English",
      "Patient and enthusiastic about teaching",
      "Minimum 4 weeks commitment",
      "Background check required",
    ],
    benefits: [
      "Accommodation provided",
      "Local orientation and support",
      "Certificate of completion",
      "Cultural immersion activities",
    ],
    applicationFormUrl: "https://forms.google.com/gkf-education-application",
    featured: true,
  },
  {
    id: "gkf-community-1",
    hostId: "gkf",
    title: "Community Development & Women Empowerment",
    description:
      "Work with local women groups on skill development, microfinance education, and community health initiatives in rural Maharashtra.",
    theme: ["community", "education"],
    location: "Pune, India",
    country: "India",
    applicantTypes: ["volunteer", "intern"],
    minDuration: 6,
    maxDuration: 12,
    images: ["/women-empowerment-workshop-india.jpg", "/community-development-rural-india.jpg"],
    requirements: [
      "Interest in social development",
      "Good communication skills",
      "Minimum 6 weeks commitment",
      "Respectful of local customs",
    ],
    benefits: ["Shared accommodation", "Meals included", "Project supervision", "Networking opportunities"],
    applicationFormUrl: "https://forms.google.com/gkf-community-application",
    featured: false,
  },
  {
    id: "wildlife-conservation-1",
    hostId: "wildlife-africa",
    title: "Wildlife Research & Conservation Field Work",
    description:
      "Participate in wildlife monitoring, data collection, and conservation efforts in the Maasai Mara. Track elephants, lions, and other iconic African species.",
    theme: ["wildlife", "environment"],
    location: "Maasai Mara, Kenya",
    country: "Kenya",
    applicantTypes: ["volunteer", "intern"],
    minDuration: 2,
    maxDuration: 12,
    images: [
      "/wildlife-researcher-tracking-elephants-africa.jpg",
      "/maasai-mara-safari-lions.jpg",
      "/conservation-field-work-kenya.jpg",
    ],
    requirements: [
      "Physical fitness for field work",
      "Interest in wildlife biology",
      "Minimum 2 weeks commitment",
      "Vaccinations up to date",
    ],
    benefits: ["Camping accommodation", "All meals provided", "Expert training", "Safari experiences"],
    applicationFormUrl: "https://forms.google.com/wildlife-africa-application",
    featured: true,
  },
  {
    id: "wildlife-veterinary-1",
    hostId: "wildlife-africa",
    title: "Veterinary Assistance & Animal Care",
    description:
      "Support our veterinary team in treating injured wildlife, conducting health checks, and maintaining animal welfare standards at our rescue center.",
    theme: ["wildlife", "medical"],
    location: "Nairobi, Kenya",
    country: "Kenya",
    applicantTypes: ["intern"],
    minDuration: 8,
    maxDuration: 24,
    images: ["/veterinarian-treating-wildlife-africa.jpg", "/placeholder.svg?height=400&width=600"],
    requirements: [
      "Veterinary or pre-vet student",
      "Experience with animals",
      "Minimum 8 weeks commitment",
      "Medical insurance required",
    ],
    benefits: [
      "Private room accommodation",
      "Meals included",
      "Hands-on veterinary experience",
      "Letter of recommendation",
    ],
    applicationFormUrl: "https://forms.google.com/wildlife-vet-application",
    featured: false,
  },
  {
    id: "heritage-archaeology-1",
    hostId: "heritage-peru",
    title: "Archaeological Site Preservation & Research",
    description:
      "Assist archaeologists in excavation, documentation, and preservation of Incan archaeological sites near Cusco. Learn ancient history hands-on.",
    theme: ["heritage", "education"],
    location: "Cusco, Peru",
    country: "Peru",
    applicantTypes: ["volunteer", "intern"],
    minDuration: 4,
    maxDuration: 16,
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    requirements: [
      "Interest in archaeology/history",
      "Physical ability for manual work",
      "Minimum 4 weeks commitment",
      "Basic Spanish helpful",
    ],
    benefits: ["Homestay accommodation", "Traditional meals", "Expert mentorship", "Site visit opportunities"],
    applicationFormUrl: "https://forms.google.com/heritage-peru-application",
    featured: true,
  },
  {
    id: "heritage-education-1",
    hostId: "heritage-peru",
    title: "Cultural Heritage Education for Local Youth",
    description:
      "Develop and deliver educational programs teaching local children about their cultural heritage, traditional crafts, and Quechua language.",
    theme: ["heritage", "education", "childcare"],
    location: "Sacred Valley, Peru",
    country: "Peru",
    applicantTypes: ["volunteer"],
    minDuration: 6,
    maxDuration: 12,
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    requirements: [
      "Experience with children",
      "Creative and adaptable",
      "Minimum 6 weeks commitment",
      "Spanish language skills preferred",
    ],
    benefits: ["Local family homestay", "Cultural immersion", "Spanish language practice", "Weekend excursions"],
    applicationFormUrl: "https://forms.google.com/heritage-education-application",
    featured: false,
  },
]

export const reviews: Review[] = [
  {
    id: "r1",
    opportunityId: "gkf-education-1",
    volunteerName: "Sarah Mitchell",
    rating: 5,
    comment:
      "Life-changing experience! The children were so eager to learn and the GKF team provided excellent support throughout my stay.",
    date: "2024-11-15",
    avatar: "/placeholder.svg?height=50&width=50",
  },
  {
    id: "r2",
    opportunityId: "wildlife-conservation-1",
    volunteerName: "James Chen",
    rating: 5,
    comment:
      "Incredible wildlife encounters and meaningful conservation work. The team is professional and passionate about their mission.",
    date: "2024-10-22",
    avatar: "/placeholder.svg?height=50&width=50",
  },
  {
    id: "r3",
    opportunityId: "heritage-archaeology-1",
    volunteerName: "Emma Rodriguez",
    rating: 4,
    comment:
      "Fascinating work at ancient sites. Learned so much about Incan civilization. Accommodation was basic but comfortable.",
    date: "2024-09-08",
    avatar: "/placeholder.svg?height=50&width=50",
  },
]
